# Generated by Django 4.2.4 on 2023-09-29 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_still_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='still',
            name='imdb_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stills', to='movies.movie'),
        ),
    ]
